// This file was auto-generated by ML.NET Model Builder. 

using System;
using ConsoleApp1ML.Model;

namespace ConsoleApp1ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Review = @"думаю если спросить у режиссера о чем собственно фильм ответ был бы банален  про любовь а вот если бы спросили у меня то я бы так и не нашла ответа почему давайте разбиратьсяв картине повествуется о девушке еве которая пытается найти свою так называемую любовь только вот взгляды у этой девушки на псевдопарней уж очень странные начнем с того что на мой взгляд героиня оказалась жуткой эгоисткой с большой буквы э но при этом все ее любят жалеют и понимают как можно произнести за весь фильм 10375 раз слово любовь но при этом относится к парням как к бездушным вещам как можно искать любовь прыгая из одной койки в другую но больше всего меня потрясла другая ситуация из фильма самые первые отношения с которых собственно все и начиналось парень денис и девушка ева живут вместе на экране мелькают картинки их чудесной совместной жизни ах как все хорошо и прекрасно но тут в кадр выходит беспощадная женская логика и что это все перевожу на человеческий язык  девушке захотелось разнообразить свой опыт скорее всего половой в первую очередь и вот она такая бедная и несчастная бросает свою первую любовь и все бы ничего он пообещал ее ждать вот казалось бы обычная фраза эту самую фразу героиня мусолит весь фильм как сво оправдание и в конечном счете нагулявшись даже обижается на него за то что он сво обещание не сдержал вот скажите госпожа режиссер что вы хотели донести до зрителя затрудняетесь ответить как я вас понимаюесли подытожить то фильм вполне неплох для того чтобы идти на фоне когда зритель занят чем то другим вникать и не дай бог анализировать данную картину не посоветую никому ах да у фильма действительно есть плюс  красивая картинка 3 из 10",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Rating with predicted Rating from sample data...\n\n");
            Console.WriteLine($"Review: {sampleData.Review}");
            Console.WriteLine($"\n\nPredicted Rating value {predictionResult.Prediction} \nPredicted Rating scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
